job/urls.py
from django.urls import path ,include
from . import views
app_name='job'
urlpatterns = [
    path('', views.job_list ,name= 'job_list'),
    path('add', views.add_job ,name='add_job'),
    path('<str:slug>', views.job_detail ,name='job_detail'), 

]

project/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls' ,namespace='accounts')),
    path('admin/', admin.site.urls),
    path('jobs/', include('job.urls' , namespace='jobs') ),
    path('contact-us/', include('contact.urls' , namespace='contact') ),
    path('api-auth/', include('rest_framework.urls'))
            ]

urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#for media file (images or videos)
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

job/models.py
from typing import Iterable, Optional
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
# Create your models here.

Job_Type= (
    ('Full Time','Full Time'),
    ('Part Time','Part Time'),
)


class Job(models.Model):
    ownerr =models.ForeignKey(User ,related_name='job_owner',on_delete=models.CASCADE)
    title =models.CharField(max_length=100)
    #location
    #job_type is part time or full time here we will use choices
    job_type=models.CharField(max_length=15 ,choices=Job_Type)
    description=models.TextField(max_length=1000)
    published_at=models.DateTimeField(auto_now=True)
    vacancy = models.IntegerField(default=1)
    salary=models.IntegerField(default=0)
    experience =models.IntegerField(default=1)
    
    # category need to know the relations
    #one to one   , one to many  , many to many
    #one to many
    category=models.ForeignKey('Category' ,on_delete=models.CASCADE)
    slug = models.SlugField(null=True ,blank=True)

    
    def save(self,*args ,**kwargs):
        self.slug=slugify(self.title)
        super(Job,self ).save(*args ,**kwargs)

    def __str__(self):
        return self.title

class Category(models.Model):
    name = models.CharField(max_length=15)

    def __str__(self):
        return self.name
    

#model to form

class Apply(models.Model):
    job = models.ForeignKey(Job ,related_name='apply_job' ,on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    email = models.EmailField()
    website = models.URLField()
    cv =models.FileField(upload_to='apply/')
    cover_letter=models.TextField(max_length=500)

    def __str__(self):
        return self.name
    




    

job/views.py
from django.urls import reverse
from django.shortcuts import redirect, render
from .models import Job
from django.core.paginator import Paginator
from .form import ApplyForm ,JobForm
from .filters import JobFilter

from django.contrib.auth.decorators import login_required




# Create your views here.
#model query set
#i want to return all jobs where is it ?? in model so i imported the job class
def job_list(request):
    job_list =Job.objects.all()


    filter = JobFilter(request.GET, queryset=job_list)
    job_list=filter.qs

    p = Paginator(job_list, 2)  # creating a paginator object
    page_number = request.GET.get('page')
    page_obj = p.get_page(page_number)
    #context : usint variable from here to html page
    #context={name in html : name_variable}
    context ={'jobs' :page_obj ,'p' :p ,'filter':filter}

    return render(request ,'job/job_list.html',context)

#id for job what i want


def job_detail(request ,slug):
    #using id to get the detecte job
    job_detail=Job.objects.get(slug =slug)

    if request.method =='POST':
        form =ApplyForm(request.POST ,request.FILES)
        if form.is_valid():
            myform =form.save(commit=False) 
            myform.job =job_detail
            myform.save()

    else :
        form =ApplyForm()


    context={'job' :job_detail , 'form':form}
    return render(request ,'job/job_details.html',context)


@login_required
def add_job(request):
    if request.method == 'POST' :
        form =JobForm(request.POST, request.FILES)
        if form.is_valid():
            myform =form.save(commit=False)
            myform.ownerr = request.user
            myform.save()
            return redirect(reverse('jobs:job_list' ,))
        
    else : 
        form =JobForm()

    return render(request , 'job/add_job.html',{'form' : form})

job/templates/job/add_job.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{%block body%}

   

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Post New Job</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                   
                   
                    <div class="apply_job_form white-bg">
                        <h4>Post New job</h4>
                        <form  method="post" class="form" enctype="multipart/form-data">
                            {% csrf_token %}
                          
                            {% bootstrap_form form %}
                            <!--
                            <div class="col-md-12">
                                {% bootstrap_button button_type="submit"  content="OK" %}
                            </div>>
                            -->
                            {% bootstrap_button content="Apply Now" button_type="submit" button_class="btn-dark col-md-12" %}
                            
                       
                        </form>
                    </div>
                </div>
             
            </div>
        </div>
    </div>

  
{%endblock body%}

job/templates/job/job_list.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{%block body%}

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{jobs.paginator.count}}+ Jobs Available</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <!-- job_listing_area_start  -->
    <div class="job_listing_area plus_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="job_filter white-bg">
                        <div class="form_inner white-bg">
                            <h3>Filter</h3>
                            <form method ="GET">
                                {% csrf_token %}
                          
                                {% bootstrap_form filter.form %}
                              
                               <button  class="boxed-btn3 w-100 mt-2" type="submit">Reset</button>

                            </form>
                        </div>
                       
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="recent_joblist_wrap">
                        <div class="recent_joblist white-bg ">
                            <div class="row align-items-center">
                                <div class="col-md-6">
                                    <h4>Job Listing</h4>
                                </div>
                                <div class="col-md-6">
                                    <div class="serch_cat d-flex justify-content-end">
                                        <select>
                                            <option data-display="Most Recent">Most Recent</option>
                                            <option value="1">Marketer</option>
                                            <option value="2">Wordpress </option>
                                            <option value="4">Designer</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="job_lists m-0">
                        <div class="row">
                            {% for job in jobs %}
                                <div class="col-lg-12 col-md-12">
                                <div class="single_jobs white-bg d-flex justify-content-between">
                                    <div class="jobs_left d-flex align-items-center">
                                        <div class="thumb">
                                            <img src="img/svg_icon/1.svg" alt="">
                                        </div>
                                        <div class="jobs_conetent">
                                            <a href="{% url 'jobs:job_detail' job.slug  %}"><h4>{{job}}</h4></a>
                                            <div class="links_locat d-flex align-items-center">
                                                <div class="location">
                                                    <p> <i class="fa fa-map-marker"></i> California, USA</p>
                                                </div>
                                                <div class="location">
                                                    <p> <i class="fa fa-clock-o"></i> {{job.job_type}}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="jobs_right">
                                        <div class="apply_now">
                                            <a class="heart_mark" href="#"> <i class="fa fa-heart"></i> </a>
                                            <a href="{% url 'jobs:job_detail' job.slug  %}" class="boxed-btn3">Apply Now</a>
                                        </div>
                                        <div class="date">
                                            <p>Date line: {{job.published_at|date:'d M o'}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        {% if jobs.has_other_pages%}
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="pagination_wrap">
                                        <ul>
                                            {% if jobs.has_previous %}
                                                <li><a href="?page={{ jobs.previous_page_number }}"> <i class="ti-angle-left"></i> </a></li>
                                            {% endif %}

                                            {% for i in jobs.paginator.page_range  %}
                                                <li><a href="?page={{i}}"><span>{{i}}</span></a></li>
                                            {% endfor %}

                                            {% if jobs.has_next %}
                                                <li><a href="?page={{ jobs.next_page_number }}"> <i class="ti-angle-right"></i> </a></li>
                                            {% endif %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- job_listing_area_end  -->

{%endblock body%}