accounts/urls.py
from django.urls import path ,include
from . import views
app_name='accounts'
urlpatterns = [
    path('signup', views.signup , name= 'signup'),
    path('profile', views.profile , name= 'profile'),
    path('profile_edit', views.profile_edit , name= 'profile_edit'),  
        ]

job/urls.py
from django.urls import path ,include
from . import views
app_name='job'
urlpatterns = [
    path('', views.job_list ,name= 'job_list'),
    path('add', views.add_job ,name='add_job'),
    path('<str:slug>', views.job_detail ,name='job_detail'), 

]

project/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls' ,namespace='accounts')),
    path('admin/', admin.site.urls),
    path('jobs/', include('job.urls' , namespace='jobs') ),
    path('contact-us/', include('contact.urls' , namespace='contact') ),
    path('api-auth/', include('rest_framework.urls'))
            ]

urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#for media file (images or videos)
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class Profile(models.Model):
    user =models.OneToOneField(User, on_delete=models.CASCADE)
    city =models.ForeignKey('City', on_delete=models.CASCADE ,null=True,blank=True)
    phone =models.CharField(max_length=15)
    image =models.ImageField( upload_to="profile/")

    def __str__(self) -> str:
        return str(self.user)

#when create user --> create empty profile 

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

class City(models.Model):
    name =models.CharField(max_length=15)
    def __str__(self) -> str:
        return self.name

accounts/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile


class SignupForm(UserCreationForm):
    class Meta:
        model= User 
        fields=['username' ,'password1','password2','email']


class UserForm(forms.ModelForm):
    class Meta:
        model= User 
        fields=['first_name','last_name','email']

class ProfileForm(forms.ModelForm):
    class Meta:
        model= Profile 
        fields=['city' ,'phone','image']

accounts/views.py
from django.shortcuts import render ,redirect
from django.contrib.auth import authenticate ,login
from django.urls import reverse
from .models import Profile
from .forms import UserForm ,ProfileForm

from .forms import SignupForm
# Create your views here.

def signup(request):
    if request.method == 'POST':
        form =SignupForm(request.POST)
        if form.is_valid():
            form.save()

            username =form.cleaned_data['username'] 
            password =form.cleaned_data['password1']

            user =authenticate(username=username ,password =password)
            login(request ,user)
            #redirect to user porfile i will build it
            return redirect('/accounts/profile')
    else :
        form =SignupForm()

    return render(request ,"registration/signup.html" ,{'form':form})


def profile(request):
    
    profile = Profile.objects.get(user= request.user)
    
    return render(request ,"accounts/profile.html" ,{'profile':profile})

    

def profile_edit(request):
    profile = Profile.objects.get(user= request.user)
    if request.method == 'POST':
        userform =UserForm(request.POST ,instance=request.user)
        profileform =ProfileForm(request.POST ,request.FILES,instance= profile )

        if userform.is_valid() and profileform.is_valid():
            userform.save()
            myprofile=profileform.save(commit=False)
            myprofile.user =request.user 
            myprofile.save()
            return redirect(reverse("accounts:profile"))
        
    else:
        userform =UserForm(instance=request.user)
        profileform =ProfileForm(instance= profile)

    return render(request ,"accounts/profile_edit.html" ,{'userform':userform ,'profileform':profileform})

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{%block body%}

    

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{job}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
               
                   
                   
                </div>
                <div class="col-lg-8 mx-auto">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Profile Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Name: <span>{{profile}}</span></li>
                                <li>Email: <span>{{profile.user.email}}</span></li>
                                <li>Phone: <span>{{profile.phone}}</span></li>
                                <li>Address: <span>{{profile.city}} </span></li>
                            </ul>
                            
                        </div>
                        <div class=" p-5 " >
                            <a href = "{% url 'accounts:profile_edit' %}" class="btn btn-success col-12">Edit Profile</a>   
                        </div>
                    </div>

                    

                   
                   
                </div>
            </div>
        </div>
    </div>

{%endblock body%}

accounts/templates/accounts/profile_edit.html
{% extends "base_generic.html" %}
{% load django_bootstrap5 %}

{% block content %}

  {% if form.errors %}
    <p>Your username and password didn't match. Please try again.</p>
  {% endif %}

  {% if next %}
    {% if user.is_authenticated %}
      <p>Your account doesn't have access to this page. To proceed,
      please login with an account that has access.</p>
    {% else %}
      <p>Please login to see this page.</p>
    {% endif %}
  {% endif %}

  <form  method="post" class="form" enctype="multipart/form-data">
    {% csrf_token %}
  
    {% bootstrap_form userform %}
    {% bootstrap_form profileform %}


    <input type="submit" value="Save" class="btn btn-success col-12">
    
  </form>

  {# Assumes you setup the password_reset view in your URLconf #}
  <p><a href="{% url 'password_reset' %}">Lost password?</a></p>

{% endblock %}